version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
    groups:
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
      svelte:
        patterns:
          - "svelte"
          - "@sveltejs/*"
      contentful:
        patterns:
          - "@contentful/*"
          - "contentful"